base_dataset: svhn
# codenames: ["leafy-planet-2310", "absurd-blaze-2311", "spring-smoke-2333"] # 62.5, [1,3,5,8]; 55.33 [1,8, 7, 2]; 0.620, [2, 4, 9]
# codenames: ["electric-armadillo-2389", "absurd-blaze-2311", "dazzling-night-2391"] # 0.444, [3, 8]; 55.33 [1,8, 7, 2];  0.28, [2, 4, 9]
codenames: ["electric-armadillo-2389", "absurd-blaze-2311", "major-sound-2388"] # 0.444, [3, 8]; 55.33 [1,8, 7, 2];  0.28, [2, 4, 9]
epochs: ["last.ckpt", "last.ckpt", "last.ckpt"]
tradition_method_filenames: []
filename: svhn_3.pkl
root: "."
num_classes: 10

