base_dataset: stl10
codenames: ["unique-glitter-1284", "unique-glitter-1284", "unique-glitter-1284"]
epochs: ["epoch=34-step=350.ckpt","epoch=39-step=400.ckpt",  "epoch=29-step=300.ckpt"]
tradition_method_filenames: []
filename: stl10_3.pkl
root: "."
num_classes: 10

